- hosts: all
  gather_facts: no
  pre_tasks:
    - name: Install Python 2 for Ansible (required current ansible)
      raw: sudo apt-get update && apt-get install -y python
  tasks:
    # Give me a user with root
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add me in the wheel group with bash
      user:
        # TODO Make this a variable.
        name: mariojv
        groups: wheel
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Set up my SSH key
      authorized_key: user=mariojv key="{{item}}"
      with_file:
       - ~/.ssh/id_rsa.pub

    - name: Kill any keys authorized to SSH as root
      file:
        path: /root/.ssh/authorized_keys
        state: absent
    # TODO Ensure state of SSH config (no password auth, no root login)
